### ISSUE TITLE
Add small description to your project

### ISSUE THREAD

**Issue by mykola-den** [hedgehogus/GoodHabits#1]
Please, create readme.md file with basic description of what is this application about.
screenshots or links to apk will be appreciated.
Example of unformatted text is [here](https://raw.githubusercontent.com/Quodnon/kottan-pokedex/master/README.md) After you created unformatted version it will look like [here](https://github.com/Quodnon/kottan-pokedex/blob/master/README.md)

To do that  make these steps:
1. Create readme.md file in your android studio in folder above **app**
2. Commit changes
3. Push changes to this repository/

P.S. This is you 
![](https://scontent-ams3-1.cdninstagram.com/t51.2885-15/e35/13398768_496379047239817_1880222927_n.jpg)

**Comment by mykola-den** [comment]
@hedgehogus, please answer next questions:
1. What is this application for?
2.  What frameworks\technology did you use?
3. Provide list of key features description.
4. Provide list of known bugs and stuff you won't fix.
5. Create `bin` folder and put there `.apk` file of your app
6. Give the url of your application in your readme
7. Add license file to your app

in the root directory create README.md file where answer questions 1-6

**Comment by Quodnon** [comment]
in the root directory create README.md file where answer questions 1-6
